spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ec_201910b
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: pepperoni.4.eg@gmail.com
    password: dohwapabsmdvcqxp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true